Car_rent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('', include('blog.urls')),
    path('api/v1/', include('webapp.api.v1.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
"""
List of URL patterns for the 'blog' app.

Each URL pattern is a `path` object that maps a URL to a view function.


URL Patterns:
- `blog/`: Displays a list of all blog posts using the `blog` view function.
- `post/<int:pk>`: Displays a single blog post specified by the primary key `pk`
   using the `post` view function.
"""
from django.urls import path

from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('blog/', blog, name='blog'),
    path('post/<int:pk>', post, name='post'),
]

webapp/urls.py
"""
Defines the URL patterns for the webapp application.

Includes views for displaying the home page, about page, car list view,
car detail view, services view, contact view, user authentication views
(login, logout, registration), and registration success view.

URL patterns:
- '' (home): index view
- 'about/': AboutView (class-based) with name 'about'
- 'cars/': CarListView (class-based) with name 'cars'
- 'cars/<int:pk>': CarDetailView (class-based) with name 'car_detail'
- 'services/': ServicesView (class-based) with name 'services'
- 'contact/': ContactView (class-based) with name 'contact'
- 'accounts/login/': CRLoginView (class-based) with name 'login'
- 'accounts/logout/': CRLogoutView (class-based) with name 'logout'
- 'accounts/register/': RegisterUserView (class-based) with name 'register'
- 'accounts/regitster/done/': RegisterDoneView (class-based) with name 'register_done'
"""
from django.urls import path

from webapp.views import *

app_name = 'webapp'

urlpatterns = [
    path('', index, name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('cars/', CarListView.as_view(), name='cars'),
    path('cars/<int:pk>', CarDetailView.as_view(), name='car_detail'),
    path('services/', ServicesView.as_view(), name='services'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('accounts/login/', CRLoginView.as_view(), name='login'),
    path('accounts/logout/', CRLogoutView.as_view(), name='logout'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/regitster/done/', RegisterDoneView.as_view(),
         name='register_done'),
]

templates/main/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <title>Car Rent &mdash; Free Website Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=DM+Sans:300,400,700&display=swap"
          rel="stylesheet">

    <link rel="stylesheet" href="{% static "webapp/fonts/icomoon/style.css" %}">

    <link rel="stylesheet" href="{% static "webapp/css/bootstrap.min.css" %}">
    <link rel="stylesheet"
          href="{% static "webapp/css/bootstrap-datepicker.css" %}">
    <link rel="stylesheet"
          href="{% static "webapp/css/jquery.fancybox.min.css" %}">
    <link rel="stylesheet"
          href="{% static "webapp/css/owl.carousel.min.css" %}">
    <link rel="stylesheet"
          href="{% static "webapp/css/owl.theme.default.min.css" %}">
    <link rel="stylesheet"
          href="{% static "webapp/fonts/flaticon/font/flaticon.css" %}">
    <link rel="stylesheet" href="{% static "webapp/css/aos.css" %}">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static "webapp/css/style.css" %}">

</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">


<div class="site-wrap" id="home-section">

    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close mt-3">
                <span class="icon-close2 js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div>


    <header class="site-navbar site-navbar-target" role="banner">

        <div class="container">
            <div class="row align-items-center position-relative">

                <div class="col-3 ">
                    <div class="site-logo">
                        <a href="{% url 'webapp:home' %}">CarRent</a>
                    </div>
                </div>

                <div class="col-9  text-right">


                    <span class="d-inline-block d-lg-none"><a href="#"
                                                              class="text-white site-menu-toggle js-menu-toggle py-5 text-white"><span
                            class="icon-menu h3 text-white"></span></a></span>


                    <nav class="site-navigation text-right ml-auto d-none d-lg-block"
                         role="navigation">
                        <ul class="site-menu main-menu js-clone-nav ml-auto ">
                            <li
                                    {% if request.resolver_match.url_name == 'home' %}
                                        class="active" {% endif %}><a
                                    href="{% url 'webapp:home' %}"
                                    class="nav-link">Home</a></li>
                            <li
                                    {% if request.resolver_match.url_name == 'services' %}
                                        class="active" {% endif %}><a
                                    href="{% url 'webapp:services' %}"
                                    class="nav-link">Services</a></li>
                            <li
                                    {% if request.resolver_match.url_name == 'cars' %}
                                        class="active" {% endif %}><a
                                    href="{% url 'webapp:cars' %}"
                                    class="nav-link">Cars</a></li>
                            <li
                                    {% if request.resolver_match.url_name == 'about' %}
                                        class="active" {% endif %}><a
                                    href="{% url 'webapp:about' %}"
                                    class="nav-link">About</a></li>
                            <li
                                    {% if request.resolver_match.url_name == 'blog'  or request.resolver_match.url_name == 'post' %}
                                        class="active" {% endif %}><a
                                    href="{% url 'blog:blog' %}"
                                    class="nav-link">Blog</a></li>
                            <li
                                    {% if request.resolver_match.url_name == 'contact' %}
                                        class="active" {% endif %}><a
                                    href="{% url 'webapp:contact' %}"
                                    class="nav-link">Contact</a></li>

                         {% if user.username %}
                                <li style="color: yellow">{{ user.username }}</li>
                                <li {% if request.resolver_match.url_name == 'logout' %}class="active"{% endif %}><a
                                        href="{% url 'webapp:logout' %}" class="nav-link">Logout</a></li>
                            {% else %}
                                <li {% if request.resolver_match.url_name == 'login' %}class="active"{% endif %}><a
                                        href="{% url 'webapp:login' %}" class="nav-link">Login</a></li>
                                <li {% if request.resolver_match.url_name == 'register' or request.resolver_match.url_name == 'register_done' %}class="active"{% endif %}>
                                    <a
                                            href="{% url 'webapp:register' %}" class="nav-link">Register</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>


            </div>
        </div>

    </header>

    {% block content %}

    {% endblock %}

    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <h2 class="footer-heading mb-4">About Us</h2>
                    <p>Far far away, behind the word mountains, far from the
                        countries Vokalia and Consonantia, there live the blind
                        texts. </p>
                </div>
                <div class="col-lg-8 ml-auto">
                    <div class="row">
                        <div class="col-lg-3">
                            <h2 class="footer-heading mb-4">Quick Links</h2>
                            <ul class="list-unstyled">
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Testimonials</a></li>
                                <li><a href="#">Terms of Service</a></li>
                                <li><a href="#">Privacy</a></li>
                                <li><a href="#">Contact Us</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-3">
                            <h2 class="footer-heading mb-4">Quick Links</h2>
                            <ul class="list-unstyled">
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Testimonials</a></li>
                                <li><a href="#">Terms of Service</a></li>
                                <li><a href="#">Privacy</a></li>
                                <li><a href="#">Contact Us</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-3">
                            <h2 class="footer-heading mb-4">Quick Links</h2>
                            <ul class="list-unstyled">
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Testimonials</a></li>
                                <li><a href="#">Terms of Service</a></li>
                                <li><a href="#">Privacy</a></li>
                                <li><a href="#">Contact Us</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-3">
                            <h2 class="footer-heading mb-4">Quick Links</h2>
                            <ul class="list-unstyled">
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Testimonials</a></li>
                                <li><a href="#">Terms of Service</a></li>
                                <li><a href="#">Privacy</a></li>
                                <li><a href="#">Contact Us</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row pt-5 mt-5 text-center">
                <div class="col-md-12">
                    <div class="border-top pt-5">
                        <p>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                            All rights reserved | This template is made with <i
                                class="icon-heart text-danger"
                                aria-hidden="true"></i> by <a
                                href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </footer>

</div>

<script src="{% static "webapp/js/jquery-3.3.1.min.js" %}"></script>
<script src="{% static "webapp/js/popper.min.js" %}"></script>
<script src="{% static "webapp/js/bootstrap.min.js" %}"></script>
<script src="{% static "webapp/js/owl.carousel.min.js" %}"></script>
<script src="{% static "webapp/js/jquery.sticky.js" %}"></script>
<script src="{% static "webapp/js/jquery.waypoints.min.js" %}"></script>
<script src="{% static "webapp/js/jquery.animateNumber.min.js" %}"></script>
<script src="{% static "webapp/js/jquery.fancybox.min.js" %}"></script>
<script src="{% static "webapp/js/jquery.easing.1.3.js" %}"></script>
<script src="{% static "webapp/js/bootstrap-datepicker.min.js" %}"></script>
<script src="{% static "webapp/js/aos.js" %}"></script>

<script src="{% static "webapp/js/main.js" %}"></script>

</body>

</html>