Car_rent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('', include('blog.urls')),
    path('api/v1/', include('webapp.api.v1.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
"""
List of URL patterns for the 'blog' app.

Each URL pattern is a `path` object that maps a URL to a view function.


URL Patterns:
- `blog/`: Displays a list of all blog posts using the `blog` view function.
- `post/<int:pk>`: Displays a single blog post specified by the primary key `pk`
   using the `post` view function.
"""
from django.urls import path

from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('blog/', blog, name='blog'),
    path('post/<int:pk>', post, name='post'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    """
      A model representing a blog post.

      Attributes:
          title (str): The title of the post, limited to 70 characters.
          created_at (datetime): The date and time at which the post was created, automatically set
              to the current date and time when the object is first saved.
          author (User): The user who created the post, referenced from the built-in Django User model.
          text_area (str): The main content of the post, as a text field.
          image (ImageField): An optional image associated with the post, uploaded to the `blog_images/`
              directory on the server.
          categories (ManyToManyField): A many-to-many relationship with the `Category` model, allowing
              the post to belong to multiple categories.
          tags (ManyToManyField): A many-to-many relationship with the `Tags` model, allowing the post
              to be tagged with multiple tags.

      Methods:
          __str__(): Returns the title of the post (used mostly for debugging and admin purposes).

      Meta:
          verbose_name (str): A human-readable name for the model in singular form.
          verbose_name_plural (str): A human-readable name for the model in plural form.
      """
    title = models.CharField(max_length=70)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text_area = models.TextField()
    image = models.ImageField(upload_to='blog_images/', blank=True)
    categories = models.ManyToManyField('Category')
    tags = models.ManyToManyField('Tags')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"


class Commentary(models.Model):
    """
    A model representing a comment made by a user on a post.

    Attributes:
        text (str): The content of the comment.
        post (Post): The post that is being commented on.
        author (User): The user who wrote the comment.
        email (str): The email address of the user who wrote the comment.
        created_at (DateTime): The date and time when the comment was created.
"""
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    email = models.EmailField(max_length=100, default='')
    created_at = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.text[:50] + '...'

    class Meta:
        verbose_name = "Commentary"
        verbose_name_plural = "Commentaries"


class Category(models.Model):
    """
       A model representing a category of blog posts.

       Attributes:
           title (str): The title of the category, up to 50 characters.

       Methods:
           __str__(): Returns a string representation of the category, which is its title.
       """
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class Tags(models.Model):
    """
       Model representing the tags for a blog post.

       Attributes:
           title (str): The title of the tag.

       Methods:
           __str__: Returns the string representation of the tag.

       Meta:
           verbose_name (str): The singular name for the model in the admin interface.
           verbose_name_plural (str): The plural name for the model in the admin interface.
       """
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

blog/forms.py
from .models import Commentary
from django import forms


class CommentForm(forms.ModelForm):
    """
        A form to create or update a Commentary instance.
        Attributes:
            model (class): A reference to the Commentary model that this form is associated with.
            fields (tuple): A tuple of field names to include in the form.
    """

    class Meta:
        model = Commentary
        fields = ('author', 'email', 'text')

        name = forms.CharField(label='Name *')
        email = forms.EmailField(label='Email *')
        message = forms.CharField(label='Message', widget=forms.Textarea(
            attrs={'class': 'form-control'}))

blog/views.py
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import render
from blog.models import Post, Commentary, Category
from blog.forms import CommentForm


def blog(request):
    """
        View function that retrieves all posts from the database, paginates them with 3 posts per page,
        and renders a blog page with the paginated posts. The current page number is obtained from the
        'page' query parameter in the request. If the requested page number is invalid, the first page
        is displayed. The context dictionary passed to the template includes the Page object for the
        current page, which provides access to the list of posts and information about pagination.
    """
    posts = Post.objects.all()
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page')
    page_objs = paginator.get_page(page_number)

    context = {"page_objs": page_objs}
    return render(request, 'blog/blog.html', context=context)


def post(request, pk):
    """
       This function handles both GET and POST requests for a particular blog post along with its comments and categories.
    """
    post = Post.objects.get(pk=pk)
    comments = Commentary.objects.filter(post_id=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.new = post
            form.save()
    else:
        form = CommentForm()

    categories = Category.objects.annotate(num_posts=Count('post'))
    context = {
        'post': post,
        'comments': comments,
        'categories': categories,
        'form': form,
    }
    return render(request, 'blog/post.html', context)

blog/templates/blog/blog.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
    <div class="ftco-blocks-cover-1">
        <div class="ftco-cover-1 overlay innerpage"
             style="background-image: url('../../static/blog/images/bg_auto.jpg')">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-lg-6 text-center">
                        <h1>Car Articles</h1>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing
                            elit.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="site-section bg-light">
        <div class="container">
            <div class="row">

                {% for post in page_objs %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="post-entry-1 h-100">
                        <a href="{% url 'blog:post' post.pk %}">
                            <img src="{{ post.image.url }}"
                                 alt="Image"
                                 class="img-fluid">
                        </a>
                        <div class="post-entry-1-contents">

                            <h2><a href="{% url 'blog:post' post.pk %}">{{ post.title }}</a></h2>
                            <span class="meta d-inline-block mb-3">{{ post.created_at }} <span
                                    class="mx-2">by</span> <a href="#">{{ post.author }}</a></span>
                            <p>{{ post.text_area|truncatechars:50 }}</p>
                        </div>
                    </div>
                </div>
               {% endfor %}

                <div class="col-12">
                    {% for page in page_objs.paginator.page_range %}
                        {% if page == page_objs.number %}
                            <a href="?page={{ page }}#my-heading" class="p-3"
                               style="color: #0b0b0b">{{ page }}</a>
                        {% else %}
                            <a href="?page={{ page }}#my-heading"
                               class="p-3">{{ page }}</a>
                        {% endif %}
                    {% endfor %}
                </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container site-section mb-5">
        <div class="row justify-content-center text-center">
            <div class="col-7 text-center mb-5">
                <h2>How it works</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Nemo assumenda, dolorum necessitatibus eius earum voluptates
                    sed!</p>
            </div>
        </div>
        <div class="how-it-works d-flex">
            <div class="step">
                <span class="number"><span>01</span></span>
                <span class="caption">Time &amp; Place</span>
            </div>
            <div class="step">
                <span class="number"><span>02</span></span>
                <span class="caption">Car</span>
            </div>
            <div class="step">
                <span class="number"><span>03</span></span>
                <span class="caption">Details</span>
            </div>
            <div class="step">
                <span class="number"><span>04</span></span>
                <span class="caption">Checkout</span>
            </div>
            <div class="step">
                <span class="number"><span>05</span></span>
                <span class="caption">Done</span>
            </div>

        </div>
    </div>

{% endblock %}

blog/templates/blog/post.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
    <div class="ftco-blocks-cover-1">
        <div class="ftco-cover-1 innerpage overlay"
             style="background-image: url('../../static/blog/images/bg_auto.jpg')">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-lg-6 text-center">
                        <span class="d-block mb-3 text-white"
                              data-aos="fade-up">{{ post.created_at}} <span
                                class="mx-2 text-primary">&bullet;</span> by {{ post.author }}</span>
                        <h1 class="mb-4" data-aos="fade-up"
                            data-aos-delay="100">{{ post.title }}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-md-8 blog-content">
                <img src="{{ post.image.url }}" alt="Image" class="img-fluid">
                    <p class="lead">{{ post.text_area }}</p>


                    <div class="pt-5">
                        <p>Categories:
                            {% for category in post.categories.all %}
                            <a href="#">{{ category.title }}</a>
                            {% endfor %}
                        {% for tag in post.tags.all %}
                            Tags: <a href="#">{{ tag.title }}</a>
                        {% endfor %}
                        </p>
                    </div>


                    <div class="pt-5">
                        <h3 class="mb-5">Comments: {{ comments.count }}</h3>
                        <ul class="comment-list">
                            {% for commentary in comments %}
                            <li class="comment">
                                <div class="vcard bio">
                                    <img src="{% static "webapp/images/person_2.jpg" %}"
                                         alt="Free Website Template by Free-Template.co">
                                </div>
                                <div class="comment-body">
                                    <h3>{{ commentary.author }}</h3>
                                    <div class="meta">{{ commentary.created_at }}
                                    </div>
                                    <p>{{ commentary.text }}</p>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                        <!-- END comment-list -->

                        <div class="comment-form-wrap pt-5">
                            <h3 class="mb-5">Leave a comment</h3>
                            <form action="#" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="name">Name *</label>
                                    <input type="text" class="form-control"
                                           id="name">
                                </div>
                                <div class="form-group">
                                    <label for="email">Email *</label>
                                    <input type="email" class="form-control"
                                           id="email">
                                </div>

                                <div class="form-group">
                                    <label for="message">Message</label>
                                    <textarea name="" id="message" cols="30"
                                              rows="10"
                                              class="form-control"></textarea>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Post Comment"
                                           class="btn btn-primary btn-md text-white">
                                </div>

                            </form>
                        </div>
                    </div>

                </div>
                <div class="col-md-4 sidebar">
                    <div class="sidebar-box">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <span class="icon fa fa-search"></span>
                                <input type="text" class="form-control"
                                       placeholder="Type a keyword and hit enter">
                            </div>
                        </form>
                    </div>
                    <div class="sidebar-box">
                        <div class="categories">
                            <h3>Categories</h3>
                            {% for category in categories %}
                            <li><a href="#">{{ category.title }} <span>({{ category.num_posts }})</span></a></li>
                            {% endfor %}

                        </div>
                    </div>
                    <div class="sidebar-box">
                        <img src="{% static "webapp/images/person_1.jpg" %}"
                             alt="Free Website Template by Free-Template.co"
                             class="img-fluid mb-4 w-50 rounded-circle">
                        <h3 class="text-black">About The Author</h3>
                        <p>Even the all-powerful Pointing has no control about
                            the blind texts it is an almost unorthographic life
                            One day however a small line of blind text by the
                            name of Lorem Ipsum decided to leave for the far
                            World of Grammar.</p>
                        <p><a href="#"
                              class="btn btn-primary btn-md text-white">Read
                            More</a></p>
                    </div>

                    <div class="sidebar-box">
                        <h3 class="text-black">Paragraph</h3>
                        <p>When she reached the first hills of the Italic
                            Mountains, she had a last view back on the skyline
                            of her hometown Bookmarksgrove, the headline of
                            Alphabet Village and the subline of her own road,
                            the Line Lane. Pityful a rethoric question ran over
                            her cheek, then she continued her way.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}